export const ActionTypes = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  USER_RETERIVEAL_SUCCESS: "USER_RETERIVEAL_SUCCESS",
  USER_RETERIVEAL_FAILURE: "USER_RETERIVEAL_FAILURE",
  CREATE_SERVER_SUCCESS: "CREATE_SERVER_SUCCESS",
  CREATE_SERVER_FAILURE: "CREATE_SERVER_FAILURE",
  JOIN_SERVER_SUCCESS: "JOIN_SERVER_SUCCESS",
  JOIN_SERVER_FAILURE: "JOIN_SERVER_FAILURE",
  DELETE_SERVER_SUCCESS: "DELETE_SERVER_SUCCESS",
  DELETE_SERVER_FAILURE: "DELETE_SERVER_FAILURE",
  RETRIEVE_SERVER_SUCCESS: "RETRIEVE_SERVER_SUCCESS",
  RETRIEVE_SERVER_FAILURE: "RETRIEVE_SERVER_FAILURE",
  DELETE_CHAT_MESSAGE_SUCCESS: "DELETE_CHAT_MESSAGE_SUCCESS",
  DELETE_CHAT_MESSAGE_FAILURE: "DELETE_CHAT_MESSAGE_FAILURE",
  UPDATE_CHAT_MESSAGE_SUCCESS: "UPDATE_CHAT_MESSAGE_SUCCESS",
  UPDATE_CHAT_MESSAGE_FAILURE: "UPDATE_CHAT_MESSAGE_FAILURE",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_FAILURE: "SEND_MESSAGE_FAILURE",
  GET_CHAT_MESSAGES_SUCCESS: "GET_CHAT_MESSAGES_SUCCESS",
  GET_CHAT_MESSAGES_FAILURE: "GET_CHAT_MESSAGES_FAILURE",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",
  RECEIVE_CHAT_MESSAGE: 'RECEIVE_CHAT_MESSAGE'
};

export const BASE_URL = 'http://127.0.0.1:8000/pshyco';